[project]
name = 'hapisetup'
version = '0.1.0'

dependencies = [
    'click'
]

[build-system]
requires = ['setuptools>=42']
build-backend = 'setuptools.build_meta'

#[project.scripts]
#hapisetup = 'hapisetup:hapisetup'

[project.entry-points."console_scripts"]
hapisetup = "hapisetup:hapisetup"